Moved library code to ldap-passwd.

diff --git a/bin/ldap-passwd b/bin/ldap-passwd
--- a/bin/ldap-passwd
+++ b/bin/ldap-passwd
@@ -35,8 +35,155 @@ Options:
      --dump-ldif              Dump LDIF and exit.
 
 __USAGE__
+--mode=askpass ) {
+	shift
+	###################################################################
+	#
+	# Prompt for a password.
+	#
+	###################################################################
+	error=0
+	if [ -t 0 ]
+	then
+		printf '%s' "${*}" >&2
+		stty -echo
+	fi
+	sed -e 'q' | grep -Fvx -e '' || error=${?}
+	if [ -t 0 ]
+	then
+		stty echo
+		echo >&2
+	fi
+	exit "${error}"
+	} && : ;;
+--mode=frontend )
+	shift
+	case ${2-} in --version )
+		me=$( which -- "${1}" || ls -d -- "${1}" )
+		exec sed -n -e '/^[^#]/q' -e 's/^#\( \(.*\)\)*$/\2/p' -- "${me}"
+	esac
+	###################################################################
+	#
+	# Modify LDAP entries.
+	#
+	###################################################################
+	# Search options.
+	export LDAPSEARCH_OPTS
+	case ${LDAPSEARCH_OPTS++} in '' )
+		for LDAPSEARCH_OPTS in '-x' '-W -x' ''
+		do
+			ldapsearch -LLLM ${LDAPSEARCH_OPTS} -s base -- \
+				1.1 > /dev/null 2>&1 && break
+		done
+	esac
+	# Defaults.
+	unset GROUP_DN USER_DN
+	# LDIF.
+	LDIF=$( LDAP_HAS_FRONTEND=+ "${@}" ) 3>&1
+	error=0
+	case ${LDIF:++} in + )
+		# Extract connection parameters.
+		while :
+		do
+			head=${LDIF%%'
+'*}
+			case ${head} in
+			'# LDAP'*=* )
+				export "${head#??}"
+				LDIF=${LDIF#"${head}"}
+				LDIF=${LDIF#'
+'}
+				;;
+			* ) break ;;
+			esac
+		done
+		;;
+	esac
+	case ${LDIF:++} in + )
+		# Modify options.
+		case ${LDAPMODIFY_OPTS++},${LDAPSEARCH_OPTS:++} in
+		+,* ) ;;
+		,   ) LDAPMODIFY_OPTS= ;;
+		,+  ) LDAPMODIFY_OPTS="${LDAPSEARCH_OPTS} -W" ;;
+		esac
+		# Prompt for the LDAP password.
+		LDAPBINDPW=${LDAPBINDPW-$(
+			exec "${0}" --mode=askpass 'Enter LDAP Password: '
+			)}
+		# Determine the URI of the master LDAP server.
+		LDAPURI=${LDAPURI-$(
+			exec "${0}" --mode=uri << __PASS__
+${LDAPBINDPW}
+__PASS__
+			)}
+		export LDAPURI
+		# Modify LDAP entries.
+		error_msg=$(
+			exec ${LDAPBINDPW:+setsid} ldapmodify -M ${LDAPMODIFY_OPTS} 2>&1 << __LDIF__
+${LDAPBINDPW:+${LDAPBINDPW}
+}${LDIF}
+__LDIF__
+			) || error=${?}
+		# Report errors.
+		error_msg=${error_msg#'Enter LDAP Password: '}
+		case ${error_msg:++} in
+		+ ) printf '%s\n' "${error_msg}" >&2 ;;
+		esac
+		case ${1##[\\/]} in *group* | *user* )
+			# Invalidate name service caches.
+			if nscd=$( which -- 'nscd' )
+			then
+				"${nscd}" -i 'group'  &&
+				"${nscd}" -i 'passwd' || :
+			fi
+		esac
+		;;
+	esac
+	exit "${error}"
+	;;
+--mode=uri )
+	###################################################################
+	#
+	# Determine the URI of the master LDAP server.
+	#
+	###################################################################
+	# Prompt for the LDAP password.
+	LDAPBINDPW=${LDAPBINDPW-$(
+		"${0}" --mode=askpass 'Enter LDAP Password: '
+		)}
+	# Loop over LDAP servers in order to handle partial replication
+	# (userPassword attributes are not always replicated).
+	error=1 error_msg=
+	for uri in ${LDAPURI-$(
+		set -- \
+			/etc/ldap/ldap.conf		\
+			~/ldaprc ~/.ldaprc ldaprc	\
+			${LDAPCONF+ "${LDAPCONF}" }	\
+			${LDAPRC+ ~/"${LDAPRC}" ~/".${LDAPRC}" "${LDAPRC}" }
+		for rc
+		do
+			[ ! -s "${rc}" ] || set -- "${@}" "${rc}"
+			shift
+		done
+		sed -e '/^URI[[:space:]]/{s///;h;};$!d;g' -- "${@}"
+		)}
+	do
+		# Passwords must never be passed as command-line arguments
+		# (using the -w option or such) due to security and privacy
+		# reasons thus use a here-document.
+		error_msg=$(
+			setsid ldapwhoami ${LDAPSEARCH_OPTS} -H "${uri}" -W << __PASS__ 2>&1
+${LDAPBINDPW}
+__PASS__
+			) && exec printf '%s\n' "${uri}" || error=${?}
+	done
+	# Report errors.
+	error_msg=${error_msg#'Enter LDAP Password: '}
+	printf '%s\n' "${error_msg:?}" >&2
+	exit "${error}"
+	;;
 esac
-${LDAP_HAS_FRONTEND:+:} exec "${0%ldap-*}ldap-chfn" --mode=frontend "${0}" "${@}"
+${LDAP_HAS_FRONTEND:+:} exec "${0%ldap-*}ldap-passwd" --mode=frontend "${0}" "${@}"
 unfold() { exec sed -e ': in' -e 'N' -e 's/\n //' -e 't in' -e 'P' -e 'D'; }
 
 ###########################################################################
@@ -181,11 +328,11 @@ __LDIF__
 	esac
 	# Prompt for the LDAP password.
 	LDAPBINDPW=${LDAPBINDPW-$(
-		exec "${0%ldap-*}ldap-chfn" --mode=askpass 'Enter LDAP Password: '
+		exec "${0}" --mode=askpass 'Enter LDAP Password: '
 		)}
 	# Determine the URI of the master LDAP server.
 	LDAPURI=${LDAPURI-$(
-		exec "${0%ldap-*}ldap-chfn" --mode=uri << __PASS__
+		exec "${0}" --mode=uri << __PASS__
 ${LDAPBINDPW}
 __PASS__
 		)}
@@ -313,14 +460,14 @@ __EOT__
 	###################################################################
 	while :
 	do
-		new_pass=$( "${0%ldap-*}ldap-chfn" --mode=askpass 'Enter new password: ' )
+		new_pass=$( "${0}" --mode=askpass 'Enter new password: ' )
 		# Passwords must never be passed as command-line arguments
 		# due to security and privacy reasons thus use a here-document.
 		if error_msg=$( pwqcheck -1 config="${config}" << __PASS__ )
 ${new_pass}
 __PASS__
 		then
-			new_pass2=$( "${0%ldap-*}ldap-chfn" --mode=askpass 'Re-type new password: ' )
+			new_pass2=$( "${0}" --mode=askpass 'Re-type new password: ' )
 			# Passwords must never be passed as command-line arguments
 			# due to security and privacy reasons thus use the built-in
 			# case compound command.
